import {
  // 联系/通讯
  Phone, PhoneCall, Mail, MailOpen, Send, MapPin, Globe, Link, ExternalLink,
  MessageCircle, MessageSquare, AtSign, Voicemail,
  // 社交/平台
  Github, BookOpen, Linkedin, Twitter, Rss, Share2, Youtube,
  // 工作/职业
  Briefcase, Building2, Building, Landmark, CircleDollarSign, Handshake,
  BadgeDollarSign, Banknote, Coins, CreditCard, Wallet, Receipt, Store,
  ShoppingBag, ShoppingCart,
  // 教育/学术
  GraduationCap, BookMarked, Library, School, PenTool, NotebookPen,
  BookCopy, BookText, Brain, Atom, Microscope, Apple,
  // 项目/技术
  FolderKanban, FolderOpen, FolderClosed, FolderPlus,
  Code, Code2, Terminal, Monitor, Laptop, Smartphone, Tablet,
  Cpu, Database, Server, Cloud, HardDrive, Wifi, Bluetooth,
  Layers, Blocks, Puzzle, Binary, Braces, FileCode, FileJson,
  GitBranch, GitMerge, GitPullRequest, GitCommit,
  Rocket, Zap, Bug, TestTube2, Cable, Plug,
  // 技能/工具
  Wrench, Settings, Cog, Hammer, Gauge, Target, Star, StarHalf,
  Crosshair, Wand2, SlidersHorizontal, ToggleLeft,
  // 奖项/成就
  Trophy, Award, Medal, Crown, BadgeCheck, Sparkles, Flag,
  ThumbsUp, PartyPopper, Flame,
  // 作品/创意
  Palette, PenLine, Brush, Image, FileText, Newspaper, Presentation,
  Music, Camera, Video, Mic, Headphones, Film, Scissors,
  Eraser, Frame, Clapperboard,
  // 个人/关于
  User, UserCircle, Heart, Smile, CircleUser, IdCard, UserPlus,
  Users, Fingerprint, Baby, PersonStanding,
  // 时间/日期
  Calendar, Clock, Timer, CalendarDays, CalendarCheck, Hourglass, AlarmClock, Cake,
  // 文件/文档
  File, FileCheck, FilePlus, FileSearch, FileSpreadsheet, FileBarChart,
  Folder, Save, Download, Upload, Clipboard, ClipboardList, ClipboardCheck,
  // 箭头/导航
  ArrowRight, ArrowUp, ArrowDown, ArrowLeft,
  ChevronRight, ChevronDown, ChevronUp, ChevronLeft,
  CornerDownRight, MoveRight, RefreshCw, Repeat, RotateCw,
  // 自然/天气
  Sun, Moon, CloudSun, Leaf, TreePine, Mountain, Flower2, Snowflake, Droplet, Wind,
  // 通用
  CheckCircle, Check, XCircle, AlertCircle, AlertTriangle, Info, HelpCircle,
  Plus, Minus, X, Circle, Square, Diamond, Hexagon, Triangle,
  Lightbulb, Bookmark, Tag, Hash, Search, Eye, EyeOff,
  Shield, ShieldCheck, Lock, Unlock, Key,
  Home, Navigation, Compass, Map,
  BarChart3, TrendingUp, PieChart, Activity, LineChart, BarChart,
  Package, Box, Archive,
  Bell, BellRing, Volume2, Speaker,
  Signal, Radio,
  Truck, Plane, Car, Ship, Train,
  HeartPulse, Stethoscope, Pill, Cross,
  type LucideIcon,
} from 'lucide-react';

/** 图标注册表：名称 → 组件 */
export const ICON_REGISTRY: Record<string, LucideIcon> = {
  // 联系/通讯
  Phone, PhoneCall, Mail, MailOpen, Send, MapPin, Globe, Link, ExternalLink,
  MessageCircle, MessageSquare, AtSign, Voicemail,
  // 社交/平台
  Github, BookOpen, Linkedin, Twitter, Rss, Share2, Youtube,
  // 工作/职业
  Briefcase, Building2, Building, Landmark, CircleDollarSign, Handshake,
  BadgeDollarSign, Banknote, Coins, CreditCard, Wallet, Receipt, Store,
  ShoppingBag, ShoppingCart,
  // 教育/学术
  GraduationCap, BookMarked, Library, School, PenTool, NotebookPen,
  BookCopy, BookText, Brain, Atom, Microscope, Apple,
  // 项目/技术
  FolderKanban, FolderOpen, FolderClosed, FolderPlus,
  Code, Code2, Terminal, Monitor, Laptop, Smartphone, Tablet,
  Cpu, Database, Server, Cloud, HardDrive, Wifi, Bluetooth,
  Layers, Blocks, Puzzle, Binary, Braces, FileCode, FileJson,
  GitBranch, GitMerge, GitPullRequest, GitCommit,
  Rocket, Zap, Bug, TestTube2, Cable, Plug,
  // 技能/工具
  Wrench, Settings, Cog, Hammer, Gauge, Target, Star, StarHalf,
  Crosshair, Wand2, SlidersHorizontal, ToggleLeft,
  // 奖项/成就
  Trophy, Award, Medal, Crown, BadgeCheck, Sparkles, Flag,
  ThumbsUp, PartyPopper, Flame,
  // 作品/创意
  Palette, PenLine, Brush, Image, FileText, Newspaper, Presentation,
  Music, Camera, Video, Mic, Headphones, Film, Scissors,
  Eraser, Frame, Clapperboard,
  // 个人/关于
  User, UserCircle, Heart, Smile, CircleUser, IdCard, UserPlus,
  Users, Fingerprint, Baby, PersonStanding,
  // 时间/日期
  Calendar, Clock, Timer, CalendarDays, CalendarCheck, Hourglass, AlarmClock, Cake,
  // 文件/文档
  File, FileCheck, FilePlus, FileSearch, FileSpreadsheet, FileBarChart,
  Folder, Save, Download, Upload, Clipboard, ClipboardList, ClipboardCheck,
  // 箭头/导航
  ArrowRight, ArrowUp, ArrowDown, ArrowLeft,
  ChevronRight, ChevronDown, ChevronUp, ChevronLeft,
  CornerDownRight, MoveRight, RefreshCw, Repeat, RotateCw,
  // 自然/天气
  Sun, Moon, CloudSun, Leaf, TreePine, Mountain, Flower2, Snowflake, Droplet, Wind,
  // 通用
  CheckCircle, Check, XCircle, AlertCircle, AlertTriangle, Info, HelpCircle,
  Plus, Minus, X, Circle, Square, Diamond, Hexagon, Triangle,
  Lightbulb, Bookmark, Tag, Hash, Search, Eye, EyeOff,
  Shield, ShieldCheck, Lock, Unlock, Key,
  Home, Navigation, Compass, Map,
  BarChart3, TrendingUp, PieChart, Activity, LineChart, BarChart,
  Package, Box, Archive,
  Bell, BellRing, Volume2, Speaker,
  Signal, Radio,
  Truck, Plane, Car, Ship, Train,
  HeartPulse, Stethoscope, Pill, Cross,
};

/** 图标分类 */
export interface IconCategory {
  labelKey: string;
  icons: string[];
}

export const ICON_CATEGORIES: IconCategory[] = [
  {
    labelKey: 'icon.contact',
    icons: ['Phone', 'PhoneCall', 'Mail', 'MailOpen', 'Send', 'MapPin', 'Globe', 'Link', 'ExternalLink', 'MessageCircle', 'MessageSquare', 'AtSign', 'Voicemail'],
  },
  {
    labelKey: 'icon.social',
    icons: ['Github', 'BookOpen', 'Linkedin', 'Twitter', 'Rss', 'Share2', 'Youtube'],
  },
  {
    labelKey: 'icon.skillTool',
    icons: [
      'Code', 'Code2', 'Terminal', 'Monitor', 'Laptop', 'Smartphone', 'Tablet',
      'Cpu', 'Database', 'Server', 'Cloud', 'HardDrive', 'Wifi', 'Bluetooth',
      'Layers', 'Blocks', 'Puzzle', 'Binary', 'Braces', 'FileCode', 'FileJson',
      'GitBranch', 'GitMerge', 'GitPullRequest', 'GitCommit',
      'Rocket', 'Zap', 'Bug', 'TestTube2', 'Cable', 'Plug',
      'Wrench', 'Settings', 'Cog', 'Hammer', 'Gauge', 'Target',
      'Star', 'StarHalf', 'Crosshair', 'Wand2', 'SlidersHorizontal', 'ToggleLeft',
    ],
  },
  {
    labelKey: 'icon.eduExp',
    icons: [
      'GraduationCap', 'BookMarked', 'Library', 'School', 'PenTool', 'NotebookPen',
      'BookCopy', 'BookText', 'Brain', 'Atom', 'Microscope', 'Apple',
      'Briefcase', 'Building2', 'Building', 'Landmark', 'CircleDollarSign', 'Handshake',
      'BadgeDollarSign', 'Banknote', 'Coins', 'CreditCard', 'Wallet', 'Receipt',
      'Store', 'ShoppingBag', 'ShoppingCart',
    ],
  },
  {
    labelKey: 'icon.awardWork',
    icons: [
      'Trophy', 'Award', 'Medal', 'Crown', 'BadgeCheck', 'Sparkles', 'Flag',
      'ThumbsUp', 'PartyPopper', 'Flame',
      'Palette', 'PenLine', 'Brush', 'Image', 'FileText', 'Newspaper', 'Presentation',
      'Music', 'Camera', 'Video', 'Mic', 'Headphones', 'Film', 'Scissors',
      'Eraser', 'Frame', 'Clapperboard',
    ],
  },
  {
    labelKey: 'icon.general',
    icons: [
      'User', 'UserCircle', 'Heart', 'Smile', 'CircleUser', 'IdCard', 'UserPlus',
      'Users', 'Fingerprint', 'Baby', 'PersonStanding',
      'Calendar', 'Clock', 'Timer', 'CalendarDays', 'CalendarCheck', 'Hourglass', 'AlarmClock',
      'File', 'FileCheck', 'FilePlus', 'FileSearch', 'FileSpreadsheet', 'FileBarChart',
      'Folder', 'FolderKanban', 'FolderOpen', 'FolderClosed', 'FolderPlus',
      'Save', 'Download', 'Upload', 'Clipboard', 'ClipboardList', 'ClipboardCheck',
      'CheckCircle', 'Check', 'XCircle', 'AlertCircle', 'AlertTriangle', 'Info', 'HelpCircle',
      'Plus', 'Minus', 'X', 'Circle', 'Square', 'Diamond', 'Hexagon', 'Triangle',
      'Lightbulb', 'Bookmark', 'Tag', 'Hash', 'Search', 'Eye', 'EyeOff',
      'Shield', 'ShieldCheck', 'Lock', 'Unlock', 'Key', 'Home',
      'BarChart3', 'BarChart', 'TrendingUp', 'PieChart', 'Activity', 'LineChart',
      'Navigation', 'Compass', 'Map',
      'Package', 'Box', 'Archive',
      'Bell', 'BellRing', 'Volume2', 'Speaker', 'Signal', 'Radio',
      'Sun', 'Moon', 'CloudSun', 'Leaf', 'TreePine', 'Mountain', 'Flower2', 'Snowflake', 'Droplet', 'Wind',
      'ArrowRight', 'ArrowUp', 'ArrowDown', 'ArrowLeft',
      'ChevronRight', 'ChevronDown', 'ChevronUp', 'ChevronLeft',
      'CornerDownRight', 'MoveRight', 'RefreshCw', 'Repeat', 'RotateCw',
      'Truck', 'Plane', 'Car', 'Ship', 'Train',
      'HeartPulse', 'Stethoscope', 'Pill', 'Cross',
    ],
  },
];

/** 图标中文关键词映射（用于搜索） */
export const ICON_KEYWORDS: Record<string, string> = {
  // 联系/通讯
  Phone: '电话 手机 通话',
  PhoneCall: '电话 来电 通话',
  Mail: '邮件 邮箱 信件',
  MailOpen: '邮件 已读 打开',
  Send: '发送 投递',
  MapPin: '地图 位置 地点 定位',
  Globe: '全球 世界 网站 网络',
  Link: '链接 网址',
  ExternalLink: '外链 跳转',
  MessageCircle: '消息 聊天 对话',
  MessageSquare: '消息 留言 评论',
  AtSign: '邮箱 地址',
  Voicemail: '语音 留言',
  // 社交/平台
  Github: '代码 开源 仓库',
  BookOpen: '知乎 阅读 书籍',
  Linkedin: '领英 职场 人脉',
  Twitter: '推特 社交',
  Rss: '订阅 资讯',
  Share2: '分享 转发',
  Youtube: '视频 频道',
  // 工作/职业
  Briefcase: '工作 职业 公文包',
  Building2: '公司 企业 大厦',
  Building: '建筑 楼房',
  Landmark: '地标 政府 银行',
  CircleDollarSign: '美元 金钱 薪资',
  Handshake: '握手 合作 商务',
  BadgeDollarSign: '工资 收入 薪酬',
  Banknote: '钞票 现金 纸币',
  Coins: '硬币 财富',
  CreditCard: '信用卡 银行卡 支付',
  Wallet: '钱包 财务',
  Receipt: '收据 发票 账单',
  Store: '商店 门店',
  ShoppingBag: '购物 商城',
  ShoppingCart: '购物车 电商',
  // 教育/学术
  GraduationCap: '毕业 学位 博士帽 教育',
  BookMarked: '书签 收藏 书籍',
  Library: '图书馆 藏书',
  School: '学校 校园',
  PenTool: '钢笔 写作 设计',
  NotebookPen: '笔记 记录',
  BookCopy: '书籍 副本 教材',
  BookText: '课本 教材 文字',
  Brain: '大脑 智慧 思维 AI',
  Atom: '原子 科学 物理',
  Microscope: '显微镜 研究 实验',
  Apple: '苹果 教育 健康',
  // 项目/技术
  FolderKanban: '看板 项目管理',
  FolderOpen: '文件夹 打开',
  FolderClosed: '文件夹 关闭',
  FolderPlus: '新建文件夹',
  Code: '代码 编程 开发',
  Code2: '代码 脚本',
  Terminal: '终端 命令行 控制台',
  Monitor: '显示器 屏幕 桌面',
  Laptop: '笔记本 电脑',
  Smartphone: '手机 移动端',
  Tablet: '平板 iPad',
  Cpu: '处理器 芯片 硬件',
  Database: '数据库 存储',
  Server: '服务器 后端',
  Cloud: '云 云计算 云端',
  HardDrive: '硬盘 存储',
  Wifi: '无线 网络 信号',
  Bluetooth: '蓝牙 无线',
  Layers: '图层 架构 分层',
  Blocks: '模块 组件 积木',
  Puzzle: '拼图 插件 扩展',
  Binary: '二进制 编码',
  Braces: '花括号 代码',
  FileCode: '代码文件 源码',
  FileJson: 'JSON 配置文件',
  GitBranch: '分支 版本',
  GitMerge: '合并 代码合并',
  GitPullRequest: '拉取请求 PR',
  GitCommit: '提交 代码提交',
  Rocket: '火箭 发射 启动 上线',
  Zap: '闪电 快速 性能',
  Bug: '缺陷 调试 修复',
  TestTube2: '测试 实验',
  Cable: '电缆 连接',
  Plug: '插头 插件 接口',
  // 技能/工具
  Wrench: '扳手 工具 维修 技能',
  Settings: '设置 配置 齿轮',
  Cog: '齿轮 机械 引擎',
  Hammer: '锤子 构建 打造',
  Gauge: '仪表 性能 指标',
  Target: '目标 瞄准 精准',
  Star: '星星 收藏 评分 精通',
  StarHalf: '半星 评分',
  Crosshair: '准星 精确 聚焦',
  Wand2: '魔棒 自动 智能',
  SlidersHorizontal: '调节 参数 滑块',
  ToggleLeft: '开关 切换',
  // 奖项/成就
  Trophy: '奖杯 冠军 荣誉',
  Award: '奖牌 荣誉 证书',
  Medal: '奖章 勋章',
  Crown: '皇冠 王冠 第一',
  BadgeCheck: '认证 徽章 已验证',
  Sparkles: '闪光 优秀 亮点',
  Flag: '旗帜 里程碑 标记',
  ThumbsUp: '点赞 好评 推荐',
  PartyPopper: '庆祝 派对 恭喜',
  Flame: '火焰 热门 热情',
  // 作品/创意
  Palette: '调色板 设计 美术',
  PenLine: '画笔 编辑 书写',
  Brush: '画刷 绘画 美术',
  Image: '图片 图像 照片',
  FileText: '文档 文本 文章',
  Newspaper: '报纸 新闻 资讯',
  Presentation: '演示 PPT 幻灯片',
  Music: '音乐 歌曲 音符',
  Camera: '相机 拍照 摄影',
  Video: '视频 录像 影片',
  Mic: '麦克风 录音 语音',
  Headphones: '耳机 音频',
  Film: '胶片 电影 影视',
  Scissors: '剪刀 裁剪 剪辑',
  Eraser: '橡皮擦 清除',
  Frame: '画框 边框',
  Clapperboard: '场记板 导演 影视',
  // 个人/关于
  User: '用户 个人 关于',
  UserCircle: '头像 用户',
  Heart: '爱心 喜欢 收藏',
  Smile: '笑脸 表情 开心',
  CircleUser: '用户 账户',
  IdCard: '身份证 证件 名片',
  UserPlus: '添加用户 注册',
  Users: '团队 群组 人员',
  Fingerprint: '指纹 身份 安全',
  Baby: '婴儿 儿童',
  PersonStanding: '人 站立 个人',
  // 时间/日期
  Calendar: '日历 日期 日程',
  Clock: '时钟 时间 经验',
  Timer: '计时器 倒计时',
  CalendarDays: '日历 日程 排期',
  CalendarCheck: '日历 已完成 签到',
  Hourglass: '沙漏 等待 时间',
  AlarmClock: '闹钟 提醒',
  // 文件/文档
  File: '文件 文档',
  FileCheck: '文件 已完成 审核',
  FilePlus: '新建文件',
  FileSearch: '搜索文件 查找',
  FileSpreadsheet: '表格 Excel 电子表格',
  FileBarChart: '报表 图表文件',
  Folder: '文件夹 目录',
  Save: '保存 存储',
  Download: '下载',
  Upload: '上传',
  Clipboard: '剪贴板 复制',
  ClipboardList: '清单 列表 待办',
  ClipboardCheck: '检查 完成 核对',
  // 图表/数据
  BarChart3: '柱状图 图表 数据',
  BarChart: '柱状图 统计',
  TrendingUp: '趋势 上升 增长',
  PieChart: '饼图 占比 分析',
  Activity: '活动 心率 监控',
  LineChart: '折线图 趋势',
  // 自然/天气
  Sun: '太阳 白天 亮色',
  Moon: '月亮 夜晚 暗色',
  CloudSun: '多云 天气',
  Leaf: '叶子 环保 自然',
  TreePine: '松树 森林 自然',
  Mountain: '山 户外 攀登',
  Flower2: '花 植物 自然',
  Snowflake: '雪花 冬天 冷冻',
  Droplet: '水滴 液体',
  Wind: '风 天气',
  // 交通/出行
  Truck: '卡车 物流 运输',
  Plane: '飞机 航空 出差',
  Car: '汽车 自驾 出行',
  Ship: '轮船 航海',
  Train: '火车 高铁 铁路',
  Navigation: '导航 方向',
  Compass: '指南针 方向 探索',
  Map: '地图 路线',
  // 通用
  CheckCircle: '勾选 完成 成功',
  Check: '勾选 确认',
  XCircle: '关闭 失败 错误',
  AlertCircle: '警告 提示 注意',
  AlertTriangle: '警告 危险 注意',
  Info: '信息 提示 帮助',
  HelpCircle: '帮助 疑问 FAQ',
  Plus: '加号 添加 新增',
  Minus: '减号 移除',
  X: '关闭 取消 删除',
  Circle: '圆形 圆点',
  Square: '方形 正方形',
  Diamond: '菱形 钻石 宝石',
  Hexagon: '六边形',
  Triangle: '三角形',
  Lightbulb: '灯泡 创意 想法',
  Bookmark: '书签 收藏 标记',
  Tag: '标签 分类 标记',
  Hash: '井号 标签 话题',
  Search: '搜索 查找 放大镜',
  Eye: '眼睛 查看 预览',
  EyeOff: '隐藏 不可见',
  Shield: '盾牌 安全 防护',
  ShieldCheck: '安全 已验证 防护',
  Lock: '锁 加密 安全',
  Unlock: '解锁 开放',
  Key: '钥匙 密码 认证',
  Home: '首页 主页 家',
  Bell: '铃铛 通知 提醒',
  BellRing: '铃铛 响铃 通知',
  Volume2: '音量 声音',
  Speaker: '扬声器 音响',
  Signal: '信号 强度',
  Radio: '广播 电台',
  Package: '包裹 打包 模块',
  Box: '盒子 容器',
  Archive: '归档 存档 历史',
  ArrowRight: '右箭头 前进 下一步',
  ArrowUp: '上箭头 上升',
  ArrowDown: '下箭头 下降',
  ArrowLeft: '左箭头 返回 上一步',
  ChevronRight: '右 展开',
  ChevronDown: '下 展开',
  ChevronUp: '上 收起',
  ChevronLeft: '左 返回',
  CornerDownRight: '右下 缩进 子项',
  MoveRight: '右移 移动',
  RefreshCw: '刷新 重新加载',
  Repeat: '重复 循环',
  RotateCw: '旋转 顺时针',
  HeartPulse: '心跳 健康 医疗',
  Stethoscope: '听诊器 医生 医疗',
  Pill: '药丸 医药',
  Cross: '十字 医疗 急救',
};

/** 模块默认图标 */
export const DEFAULT_MODULE_ICONS: Record<string, string> = {
  profile: 'IdCard',
  educationList: 'GraduationCap',
  workExpList: 'Briefcase',
  projectList: 'FolderKanban',
  skillList: 'Wrench',
  awardList: 'Trophy',
  workList: 'Palette',
  aboutme: 'User',
};

/** Profile 字段默认图标 */
export const DEFAULT_PROFILE_ICONS: Record<string, string> = {
  mobile: 'Phone',
  email: 'Mail',
  workPlace: 'MapPin',
  age: 'Cake',
  workExpYear: 'Clock',
};
